// ============================================================
// Fix & Flip Analyzer — Hard Money Lender Directory
// ============================================================

export interface HardMoneyLender {
  name: string;
  website: string;
  type: 'national' | 'regional';
  states: string; // "Nationwide" or specific states
  loanTypes: string[];
  ltvMax: string;
  rateRange: string;
  pointsRange: string;
  termRange: string;
  minLoan: string;
  maxLoan: string;
  closingSpeed: string;
  notes: string;
}

export const HARD_MONEY_LENDERS: HardMoneyLender[] = [
  {
    name: 'Kiavi (formerly LendingHome)',
    website: 'https://www.kiavi.com',
    type: 'national',
    states: 'Nationwide (45+ states)',
    loanTypes: ['Fix & Flip', 'Bridge', 'Rental'],
   ltvMax: '90% LTC / 75% ARV',
    rateRange: '9.25% - 13%',
    pointsRange: '1 - 2 pts',
    termRange: '12 - 24 months',
    minLoan: '$100,000',
    maxLoan: '$3,000,000',
    closingSpeed: '10 - 15 days',
    notes: 'Tech-forward platform, fast online application. No minimum experience required for some programs.',
  },
  {
    name: 'Lima One Capital',
    website: 'https://www.limaone.com',
    type: 'national',
    states: 'Nationwide (46 states)',
    loanTypes: ['Fix & Flip', 'Bridge', 'Rental', 'New Construction'],
    ltvMax: '90% LTC / 70% ARV',
    rateRange: '9.5% - 12%',
    pointsRange: '1.5 - 3 pts',
    termRange: '13 - 24 months',
    minLoan: '$75,000',
    maxLoan: '$5,000,000',
    closingSpeed: '14 - 21 days',
    notes: 'Full-service lender with dedicated loan officers. Offers new construction loans.',
  },
  {
    name: 'RCN Capital',
    website: 'https://www.rcncapital.com',
    type: 'national',
    states: 'Nationwide',
    loanTypes: ['Fix & Flip', 'Bridge', 'Long-Term Rental'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '9.99% - 12%',
    pointsRange: '1.5 - 3 pts',
    termRange: '12 - 18 months',
    minLoan: '$50,000',
    maxLoan: '$2,500,000',
    closingSpeed: '10 - 14 days',
    notes: 'Works with brokers and direct borrowers. Competitive rates for experienced investors.',
  },
  {
    name: 'CoreVest Finance',
    website: 'https://www.corevest.com',
    type: 'national',
    states: 'Nationwide',
    loanTypes: ['Fix & Flip', 'Bridge', 'Rental Portfolio'],
    ltvMax: '85% LTC / 70% ARV',
    rateRange: '8.5% - 11%',
    pointsRange: '1 - 2 pts',
    termRange: '12 - 24 months',
    minLoan: '$150,000',
    maxLoan: '$50,000,000',
    closingSpeed: '14 - 21 days',
    notes: 'Institutional-grade lender. Best for experienced investors with larger portfolios.',
  },
  {
    name: 'Groundfloor',
    website: 'https://www.groundfloor.com',
    type: 'national',
    states: 'Nationwide (30+ states)',
    loanTypes: ['Fix & Flip', 'Bridge'],
    ltvMax: '90% LTC / 70% ARV',
    rateRange: '7.5% - 14%',
    pointsRange: '2 - 4 pts',
    termRange: '6 - 18 months',
    minLoan: '$50,000',
    maxLoan: '$1,000,000',
    closingSpeed: '14 - 21 days',
    notes: 'Crowdfunded model offers competitive rates. Good for newer investors.',
  },
  {
    name: 'Visio Lending',
    website: 'https://www.visiolending.com',
    type: 'national',
    states: 'Nationwide',
    loanTypes: ['Rental (DSCR)', 'Short-Term Rental'],
    ltvMax: '80% LTV',
    rateRange: '7.5% - 10%',
    pointsRange: '0 - 2 pts',
    termRange: '30-year fixed / 5-year ARM',
    minLoan: '$75,000',
    maxLoan: '$2,000,000',
    closingSpeed: '21 - 30 days',
    notes: 'Specializes in DSCR rental loans. Great for buy-and-hold exit strategy.',
  },
  {
    name: 'Fund That Flip (now Upright)',
    website: 'https://www.upright.us',
    type: 'national',
    states: 'Nationwide (40+ states)',
    loanTypes: ['Fix & Flip', 'Bridge', 'New Construction'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '9% - 12%',
    pointsRange: '1.5 - 3 pts',
    termRange: '12 - 18 months',
    minLoan: '$100,000',
    maxLoan: '$5,000,000',
    closingSpeed: '7 - 14 days',
    notes: 'Fast closings, tech-enabled platform. Offers draw schedules for rehab funds.',
  },
  {
    name: 'Anchor Loans',
    website: 'https://www.anchorloans.com',
    type: 'national',
    states: 'Nationwide',
    loanTypes: ['Fix & Flip', 'Bridge', 'Rental'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '9.5% - 12%',
    pointsRange: '1.5 - 2.5 pts',
    termRange: '12 - 24 months',
    minLoan: '$50,000',
    maxLoan: '$5,000,000',
    closingSpeed: '7 - 10 days',
    notes: 'One of the largest private lenders. Very fast closings for experienced borrowers.',
  },
  {
    name: 'Easy Street Capital',
    website: 'https://www.easystreetcap.com',
    type: 'national',
    states: 'Nationwide (40+ states)',
    loanTypes: ['Fix & Flip', 'DSCR Rental', 'Bridge'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '9% - 12%',
    pointsRange: '1 - 2 pts',
    termRange: '12 - 24 months',
    minLoan: '$75,000',
    maxLoan: '$3,000,000',
    closingSpeed: '10 - 14 days',
    notes: 'Investor-friendly terms. No prepayment penalties on fix & flip loans.',
  },
  {
    name: 'New Silver',
    website: 'https://www.newsilver.com',
    type: 'national',
    states: 'Nationwide (39 states)',
    loanTypes: ['Fix & Flip', 'Rental', 'Ground-Up'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '9.5% - 12.5%',
    pointsRange: '1 - 3 pts',
    termRange: '12 - 24 months',
    minLoan: '$100,000',
    maxLoan: '$5,000,000',
    closingSpeed: '5 - 10 days',
    notes: 'Fully online process. Some of the fastest closings in the industry.',
  },
  {
    name: 'Lending One',
    website: 'https://www.lendingone.com',
    type: 'national',
    states: 'Nationwide (47 states)',
    loanTypes: ['Fix & Flip', 'Bridge', 'Rental', 'Portfolio'],
    ltvMax: '90% LTC / 75% ARV',
    rateRange: '8.99% - 11.99%',
    pointsRange: '1 - 2 pts',
    termRange: '12 - 24 months',
    minLoan: '$75,000',
    maxLoan: '$10,000,000',
    closingSpeed: '10 - 14 days',
    notes: 'Competitive rates for repeat borrowers. Volume discounts available.',
  },
  {
    name: 'Residential Capital Partners',
    website: 'https://www.rescappartners.com',
    type: 'regional',
    states: 'TX, CO, GA, NC, FL, TN',
    loanTypes: ['Fix & Flip', 'Bridge'],
    ltvMax: '85% LTC / 70% ARV',
    rateRange: '10% - 13%',
    pointsRange: '2 - 3 pts',
    termRange: '6 - 12 months',
    minLoan: '$50,000',
    maxLoan: '$1,500,000',
    closingSpeed: '7 - 14 days',
    notes: 'Strong in Texas and Southeast markets. Relationship-based lending.',
  },
];
