CREATE TABLE `deal_photos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealUniqueId` varchar(64) NOT NULL,
	`userId` int,
	`url` text NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`filename` varchar(255),
	`mimeType` varchar(64),
	`caption` varchar(255),
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `deal_photos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `saved_deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`uniqueId` varchar(64) NOT NULL,
	`userId` int,
	`address` varchar(255) NOT NULL,
	`city` varchar(128) NOT NULL,
	`state` varchar(32) NOT NULL,
	`zip` varchar(16) NOT NULL,
	`purchasePrice` int NOT NULL,
	`arv` int NOT NULL,
	`rehabCost` int NOT NULL,
	`totalInvestment` int NOT NULL,
	`netProfit` int NOT NULL,
	`roiBps` int NOT NULL,
	`dealVerdict` varchar(32) NOT NULL,
	`maxAllowableOffer` int NOT NULL,
	`recommendedMaxPrice` int NOT NULL,
	`targetROI` int NOT NULL,
	`sqft` int NOT NULL,
	`beds` int NOT NULL,
	`baths` int NOT NULL,
	`yearBuilt` int NOT NULL,
	`market` varchar(128),
	`dealScore` int,
	`cashOnCashBps` int,
	`status` enum('active','under_contract','closed','passed','archived') NOT NULL DEFAULT 'active',
	`starred` int NOT NULL DEFAULT 0,
	`notes` text,
	`dealData` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `saved_deals_id` PRIMARY KEY(`id`),
	CONSTRAINT `saved_deals_uniqueId_unique` UNIQUE(`uniqueId`)
);
